
#	darwin_i386_bashrc

bashrcPath=~/.bash_darwin_i386
## USER FUNCTIONS
if [ -f "${bashrcPath}/functions" ]; then
	source "${bashrcPath}/functions"
fi

## USER ALIASES
if [ -f "${bashrcPath}/aliases" ]; then
	source "${bashrcPath}/aliases"
fi
